### ISSUE TITLE
Create private ECR Image for Terraform Lambda Container

### ISSUE THREAD

**Issue by hskiba** [frgrisk/terraform-aws-turbo-deploy#3]
Right now, the module builds a docker container by shelling out to the OS. This means that the host running `terraform apply` needs to have Docker installed and sufficient space, etc. to build the container. Instead, publish a public container to ECR, and reference it in this module. The container source and build should happen as part of the https://github.com/frgrisk/turbo-deploy repo (I think you'll need to move some stuff from this repo to there).

**Comment by zeteoh** [comment]
might need some help here, tried this yesterday and i ran into some issue, tried with docker hub as well

**Comment by luqmanbazran** [comment]
I'll give it a try

**Comment by zeteoh** [comment]
With @luqmanbazran help, we discovered that Lambda does not currently support using images from ECR Public
1. https://stackoverflow.com/questions/67330890/using-a-public-ecr-image-for-lambda-function
2. https://repost.aws/questions/QUEgw2bC3aTV2hmssdD5bYfA/how-to-use-a-public-ecr-with-aws-lambda
